### ISSUE TITLE
NavBarDrawer:  whitespace padding above and below logo

### ISSUE THREAD

**Issue by MaxJGruber** [sdsna/sdgindex-starter#8]
Remove unwanted whitespaces above and below the logo in the navigation drawer on mobile.

PS: Needs to be integrated back into sdgindex-starter, too.

Before:
image

After:
image

**Comment by MaxJGruber** [comment]
![image](https://user-images.githubusercontent.com/66439451/175077021-4b7cc90e-5700-432a-bf28-7ec3134c53ff.png)

@SaraKasim If you have time, can you fix this too please?

**Comment by SaraKasim** [comment]
It should be fixed now. I created a new branch just in case 😶
